# Generated by Django 4.0 on 2023-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_employeeexperince_employeeeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperince',
            name='company2duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
